personal_portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('portfolio.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.HomeProjects.as_view(), name='home'),
    path('category/<int:category_id>/', views.CategoryProjects.as_view(),
         name='get_category'),
    path('project/<int:pk>/', views.ViewProject.as_view(),
         name='view_project'),
    path('project/add_project', views.CreateProject.as_view(),
         name='add_project'),

    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('test/', views.contact, name='contact'),
]

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'portfolio:home' %}">Портфолио</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:home' %}">Главная</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:contact' %}">Контакты</a></li>

                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:add_project' %}">Добавить проект</a></li>
                {% endif %}

            </ul>
            {% if request.user.is_authenticated %}
                Добро пожаловать, {{ user.username }} | <a
                href="{% url 'portfolio:user_logout' %}">Выход</a>
            {% else %}
                <span class="navbar-text">
                    <a href="{% url 'portfolio:register' %}">Регистрация</a> |
                    <a href="{% url 'portfolio:user_login' %}">Авторизация</a>
                </span>
            {% endif %}


        </div>
    </div>
</nav>

templates/inc/_sidebar.html
{% load portfolio_tags %}


{% get_list_categories as categories%}

<div class="list-group">
    {% for category in categories %}
    <a href="{{ category.get_absolute_url }}"
       class="list-group-item list-group-item-action">{{ category.title }}  <span class="badge bg-primary rounded-pill">{{ category.cnt }}</span></a>
    {% endfor %}
</div>
<br>

{% comment %}
{% show_categories %}
{% endcomment %}